### ISSUE TITLE
TableViews

### ISSUE THREAD

**Issue by brianpattison** [ebryn/ember-titanium#15]
Hey, it's been a while! :)

I'm not ready to submit a Pull Request, but I wanted to get your opinion on what I've been working on for the last few hours:

https://github.com/brianpattison/sproutcore-titanium/commit/54683aec9e9e27c78e2a575eb7c5a3f229a59fdc

I'd love to know if you think I'm going in the right direction. Any feedback is greatly appreciated!

**Comment by ebryn** [comment]
Hey Brian,

Made a couple comments. Glad to see you working on this. I haven't had
time to work on SCTi lately :(
- Erik

On Sun, Nov 27, 2011 at 5:23 PM, Brian Pattison
reply@reply.github.com
wrote:
