### ISSUE TITLE
Need for a less inclusive base class than SCTi.View 

### ISSUE THREAD

**Issue by brianpattison** [ebryn/ember-titanium#4]
SCTi.AlertDialog extending SCTi.View doesn't make sense. We need a base class that doesn't have any properties or child views.

We should also be using SproutCore Mixins. Have a mixin called SCTi.Openable rather than TabGroup extending the Window class. TabGroup doesn't really share any properties, methods, or events with Window other than open() and close().

**Comment by ebryn** [comment]
Sounds good, like your approach in the pull request.
