### ISSUE TITLE
Initial bindings out of sync

### ISSUE THREAD

**Issue by brianpattison** [ebryn/ember-titanium#8]
I'm trying to adapt my little demo to `sproutcore-titanium` and running into this issue.

Link: https://github.com/brianpattison/sproutcore-titanium-bindings/blob/edge/Resources/app.js

The first couple SCTi controls on the first window that have bindings to `ExampleApp.exampleOneController.title` load without an initial value.

I guess I don't know enough about the SproutCore RunLoop to know where it's going wrong. I just know if I hack it by wrapping `tabGroup.open()` with `setTimeout` it works.

**Comment by ebryn** [comment]
This was a bug in your branch related to super not getting called in the correct order.
